# Generated by Django 5.0.2 on 2024-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
